### ISSUE TITLE
update HDFView?

### ISSUE THREAD

**Issue by rijobro** [SyneRBI/SyneRBI_VM#129]
We currently get HDFView from `apt-install`. However, this is version 2.11 and @evgueni-ovtchinnikov has reported this to be too out of date to open certain files. We would therefore like to upgrade to version 3. 

Putting this to milestone 2.0 but can get pushed back if not possible.

**Comment by KrisThielemans** [comment]
let's drop it from the `apt` list of  packages. Can later on add on wiki a pointer to instructions on how to build it.

@paskino, this might be for the docker stuff in the SIRF-SuperBuild as well.

**Comment by KrisThielemans** [comment]
this could probably be closed. @paskino, please check. If not, reassign to 2.2

**Comment by KrisThielemans** [comment]
could try https://askubuntu.com/questions/907159/hdfview-doesnt-open-files-on-ubuntu-17-04 but sounds difficult

**Comment by paskino** [comment]
Binary files of [HDFView ](https://www.hdfgroup.org/downloads/hdfview/#download)requires sign in to the HDF group to download.

It could be possible to build HDFView as part of the SuperBuild, but it'll require a Java JDK (they don't say which version, I suppose 8 would do, though they built the binaries with 15), and Apache ANT.

Do we want to go this way?

**Comment by KrisThielemans** [comment]
nope. I wouldn't.
