### ISSUE TITLE
VGA Script requires additional installation

### ISSUE THREAD

**Issue by johannesmayer** [SyneRBI/SyneRBI_VM#149]
Before running the update_VGA.sh script one needs to run this command for some reason:

sudo apt install linux-headers-$(uname -r)

**Comment by KrisThielemans** [comment]
We need to add this to the wiki/doc where we say how to update the VGA. But I'd also add it in `update_VGA.sh` (then without the `sudo`).

**Comment by KrisThielemans** [comment]
this hit me again. @paskino, can you take care of this please?

**Comment by KrisThielemans** [comment]
it needs to be in the Vagrant file as well such that it's done at the start. Possibly in `update_VGA` check if it's there already and then don't bother, but as `apt` already does that for us, that seems overkill.

**Comment by paskino** [comment]
Yes, I guess we need to install the linux headers at VM creation time, in the apt installed packages.

I've never seen this as during initial run the VGA for the running VirtualBox is installed.
