### ISSUE TITLE
use Ubuntu 20.04 from > 2.2 release

### ISSUE THREAD

**Issue by paskino** [SyneRBI/SyneRBI_VM#167]
As Ubuntu 20.04 LTS has been released it seems a good idea to move to the this new OS.

**Comment by KrisThielemans** [comment]
@paskino, we have multiple problems with the SIRF-exercises. want to give this a go if it happens to work already?

**Comment by KrisThielemans** [comment]
duplicate  #158 

Also, forget about doing this before 2.2. But start soon after :wink:
