### ISSUE TITLE
pip installs nbstripout latest and is not compatible with python2

### ISSUE THREAD

**Issue by paskino** [SyneRBI/SyneRBI_VM#169]
I just found 2 bugs:

1. [`UPDATE.sh`](https://github.com/SyneRBI/SyneRBI_VM/blob/master/scripts/UPDATE.sh#L143) installs `nbstripout` instead of `INSTALL_python_packages.sh`
1. pip installs latest version and it is [incompatible ](https://github.com/kynan/nbstripout/issues/128)with python 2.7

**Comment by paskino** [comment]
The first is not a real bug. 
The second is fixed by 1642bd794de08fdbc185fc50f70e3e6c1ed41284

**Comment by casperdcl** [comment]
:thinking: opened https://github.com/kynan/nbstripout/pull/129
