### ISSUE TITLE
Build problems SIRF VM 2.2.0 Python3

### ISSUE THREAD

**Issue by Ede1994** [SyneRBI/SyneRBI_VM#178]
I've created an issue in SyneRBI/SIRF-Exercises (https://github.com/SyneRBI/SIRF-Exercises/issues/63). After this I checked:
```
cd devel/buildVM/sources/SIRF
git status
```
which brought the following result: HEAD detached at v2.2.0

I did the following and created some terminal outputs (.zip-Folder):
```
update_VM.sh -t origin/master -> update_vm_output.txt
cd ~/devel/buildVM
cmake -DSIRF_TAG=origin/master . -> cmake.txt
cd sources/SIRF
git checkout origin/master
cd ../..
make -j3 -> make.txt
```
`make` fails with:
```
[ 78%] Performing update step for 'SIRF'
*** Please tell me who you are.
Run
git config --global user.email you@example.com
git config --global user.name "Your Name"
to set your account's default identity.
Omit --global to set the identity only in this repository.
fatal: empty ident name (for sirfuser@vagrant.vm) not allowed
Cannot save the current index state
CMake Error at /home/sirfuser/devel/buildVM/builds/SIRF/tmp/SIRF-gitupdate.cmake:80 (message):
Failed to stash changes
```

I checked `git status` again: HEAD detached origin/master

[Outputs.zip](https://github.com/SyneRBI/SyneRBI_VM/files/6327422/Outputs.zip)

**Comment by KrisThielemans** [comment]
Not sure what went on here, but this might be specific on how you modified files. I'll close it for now as it seems to work on the new VM
