### ISSUE TITLE
set BUILD_CIL=ON

### ISSUE THREAD

**Issue by KrisThielemans** [SyneRBI/SyneRBI_VM#181]
I think we said to do this at 3.1, but up to @paskino

**Comment by KrisThielemans** [comment]
@paskino, can you please check if this is needed for the training school?

**Comment by KrisThielemans** [comment]
Presumably this needs resolving #187, #188, #189

**Comment by paskino** [comment]
I believe that the best strategy is to continue building `CIL_LITE` and use `update_VM_to_full_CIL.sh` to achieve the result wanted, see #195

**Comment by KrisThielemans** [comment]
great idea. We just need to put this in our school instructions then.
