### ISSUE TITLE
update_VM_to_full_CIL.sh fails for 2 reasons

### ISSUE THREAD

**Issue by KrisThielemans** [SyneRBI/SyneRBI_VM#187]
error during building
```
[ 54%] Performing configure step for 'astra-toolbox'
./autogen.sh: line 3: aclocal: command not found
Error running aclocal
```
Note that it keeps on going and clones CIL-demos anyway, but that has another error
```
 55%] Completed 'TomoPhantom'
[ 55%] Built target TomoPhantom
Makefile:114: recipe for target 'all' failed
make: *** [all] Error 2
Cloning into 'CIL-Demos'...
remote: Enumerating objects: 323, done.
remote: Counting objects: 100% (11/11), done.
remote: Compressing objects: 100% (7/7), done.
remote: Total 323 (delta 4), reused 4 (delta 4), pack-reused 312
Receiving objects: 100% (323/323), 46.23 MiB | 2.11 MiB/s, done.
Resolving deltas: 100% (134/134), done.
/usr/bin/python: No module named pip
All done
```
So the install is calling the wrong python.

**Comment by KrisThielemans** [comment]
Needs
```
sudo apt install autotools-dev automake
```
as part of the script, and a `python3` at the end. Best to remove the `--user` option as well from the `pip`. Apparently no longer needed/recommended with `python3` (says @casperdcl ).

**Comment by KrisThielemans** [comment]
Installing the packages after the failed run gives another error
```
** Please tell me who you are.

Run

  git config --global user.email "you@example.com"
  git config --global user.name "Your Name"

to set your account's default identity.
Omit --global to set the identity only in this repository.

fatal: empty ident name (for <sirfuser@vagrant.vm>) not allowed
Cannot save the current index state
CMake Error at /home/sirfuser/devel/buildVM/builds/astra-toolbox/tmp/astra-toolbox-gitupdate.cmake:80 (message):
  Failed to stash changes
```
Checking
```
$ cd ~/devel/buildVM/sources/astra-toolbox/
$ git status
HEAD detached at origin/master
Untracked files:
  (use "git add <file>..." to include in what will be committed)

	python_build
	python_install
```
Is this an astra bug?

**Comment by KrisThielemans** [comment]
Manually removing `astra-toolbox` from both `sources` and `builds` gives
```
[ 55%] Performing configure step for 'astra-toolbox'
configure.ac:42: error: possibly undefined macro: AC_PROG_LIBTOOL
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.
Error running autoconf
```

**Comment by paskino** [comment]
> ```
> $ cd ~/devel/buildVM/sources/astra-toolbox/
> $ git status
> HEAD detached at origin/master
> Untracked files:
>   (use "git add <file>..." to include in what will be committed)
> 
> 	python_build
> 	python_install
> ```
> 
> Is this an astra bug? (i.e. should these be in their `.gitignore`?)

This is my fault. I [create these files](https://github.com/SyneRBI/SIRF-SuperBuild/blob/eb022172a8e824cb01d415a91037d25d5a0d8a0a/SuperBuild/External_astra-toolbox.cmake#L85) in order to be able to build astra.

I see 2 options:
1.  add them to `.gitignore`
2. remove them in the SuperBuild

I am afraid we will not be able to do 2 if the configure/build/install steps fail? 1 seems more robust.

**Comment by paskino** [comment]
will be cosed by https://github.com/SyneRBI/SIRF-SuperBuild/pull/600
