### ISSUE TITLE
Astra fails to build because of cython3

### ISSUE THREAD

**Issue by ashgillman** [SyneRBI/SyneRBI_VM#188]
I was updating Michael's VM and ran into issues due to this line:

https://github.com/SyneRBI/SyneRBI_VM/blob/master/scripts/UPDATE.sh#L146

On his VM (maybe we did something funny) the executable is `/usr/bin/cython`. Perhaps it makes sense to check these executables before changing the configuration in CMake?

**Comment by paskino** [comment]
I think the newest VMs where I managed to remove reference to python2 (like in your case) should have cython3 installed rather than cython (from apt)

**Comment by ashgillman** [comment]
I am closing this - indeed this was on an older VM version so is no longer relevant
