### ISSUE TITLE
Should update_VM.sh run download_data.sh in SIRF-Exercises?

### ISSUE THREAD

**Issue by ashgillman** [SyneRBI/SyneRBI_VM#190]
I have no strong opinion here, but we had forgotten and had an error when we ran the exercises. Of course, the error message directly told us to run this script so it is very transparent.

**Comment by ashgillman** [comment]
It would make this script very slow the first time (although its already not particularly fast)

**Comment by KrisThielemans** [comment]
I don't think it should. People might want to get the VM for STIR, for CIL, or whatever. Adding a more than 1GB download isn't quite an "update" more an "upgrade". (By the way, arguably our `update_VM_to_full_xxx.sh` should have been called `upgrade_VM...` I guess!)
