### ISSUE TITLE
problem running current VM with Log error in VBox

### ISSUE THREAD

**Issue by KrisThielemans** [SyneRBI/SyneRBI_VM#58]
See 
https://github.com/joelhandwell/ubuntu_vagrant_boxes/issues/1

we need to export a new box therefore.

**Comment by casperdcl** [comment]
btw (not realated to this issue) using '-DUSE_ITK=ON' makes the uncompressed docker image 700MB larger.

**Comment by KrisThielemans** [comment]
Disabling the serial port makes the VM hang. The cause and (hopefully) work-around is described here
https://askubuntu.com/questions/771871/16-04-virtualbox-vm-from-vhd-file-hangs-at-non-blocking-pool-is-initialized

**Comment by paskino** [comment]
Adding this to the Vagrantfile should do.
```
sed -i 's/ console=ttyS0//' /etc/default//grub.d/50-cloudimg-settings.cfg
update-grub
```
The only other thing would be to **manually** remove the serial port on the VM settings.

**Comment by KrisThielemans** [comment]
what about the fix in the issue quoted above?
```
  v.customize [ "modifyvm", :id, "--uartmode1", "disconnected" ]
```

**Comment by paskino** [comment]
I kind of understood that the problem is ubuntu which requires the serial port for grub.

So far I fixed the VM with the second trick and I'm currently uploading it. 
I will later try to create a brand new VM adding `-uartmode1 disconnected`

**Comment by KrisThielemans** [comment]
not 100% sure that this will do. I think the VM might still be configured to use the serial port, and therefore have the log file, even if Ubuntu is never going to use it.
I think you'll need both... (Of course, it is possible that if you disable the serial port of the VM, and then export, that VirtualBox doesn't store the path to the log file and everything will be fine). I guess someone will have to test. not sure if I can this weekend.

**Comment by paskino** [comment]
I tried `v.customize [ "modifyvm", :id, "--uartmode1", "disconnected" ]`, but did not make any change. 

According to [this](https://askubuntu.com/questions/771871/16-04-virtualbox-vm-from-vhd-file-hangs-at-non-blocking-pool-is-initialized) it would also be very dangerous as the grub package in Ubuntu 16.04 expects the serial port, so removing it at the machine creation might just bring troubles.

**Comment by KrisThielemans** [comment]
I'm a bit confused by this. you modified grub not to use the serial part, and you modify the vagrantfile to remove the serial port. seems ok to me. Maybe it's just that we cannot do it in the desired order?

**Comment by paskino** [comment]
Exactly. We cannot influence the initial state of the Ubuntu box which requires the serial port.

**Comment by paskino** [comment]
We have a manual workaround for the current ubuntu box.

**Comment by KrisThielemans** [comment]
ok. as long as it's clearly documented.

**Comment by paskino** [comment]
Maybe I could modify just the ubuntu box and put it on vagrant to be downloaded by Vagrant. It shouldn't have the serial port problem then.

**Comment by KrisThielemans** [comment]
you could, but it's extra hassle. I have no idea how easy this is (and more importantly, we'd have to keep it up to date...). 

If this really cannot be fixed from the Vagrantfile, it seems to me that this is an issue that the Ubuntu people should fix (seems implied in the post that I originally quoted).

**Comment by KrisThielemans** [comment]
this is outdated
