### ISSUE TITLE
VM starts as bash shell sometimes (Ubuntu GUI fails to start)

### ISSUE THREAD

**Issue by evgueni-ovtchinnikov** [SyneRBI/SyneRBI_VM#77]
New VM starts ok first time, but when started after shutdown would only get as far as ubuntu-xenial login: prompt. Login as sirfuser starts bash shell.

**Comment by KrisThielemans** [comment]
This is X server stuff again. most likely your VB is out-of-date?

**Comment by evgueni-ovtchinnikov** [comment]
I am using 5.2.8, the latest so far as I can see from VB site.

**Comment by KrisThielemans** [comment]
ok. too bad. This will then be a problem with Ubuntu/the Vagrant box/VBox. Sigh. will presumably have to be flagged upstream, but not sure where...

Maybe try a "sudo apt-get update;sudo apt-get upgrade" and hope it disappears...

**Comment by evgueni-ovtchinnikov** [comment]
No, update+upgrade did not help

**Comment by paskino** [comment]
I've installed the VGA for 5.2.8, so that should work. At any rate, could you please test whether installing VGA to your VM solves the problem?

open a terminal

```
sudo mount -t iso9660 /dev/cdrom /media
sudo /media/VBoxLinuxAdditions.run
sudo shutdown -r now
```

**Comment by evgueni-ovtchinnikov** [comment]
mount: no medium found on /dev/sr0

**Comment by paskino** [comment]
try `sudo mount -t iso9660 /dev/cdrom /media` instead

**Comment by evgueni-ovtchinnikov** [comment]
sudo mount -t iso9660 /dev/cdrom /media 
instead of
sudo mount -t iso9660 /dev/cdrom /media
?
(looks identical to me)

**Comment by paskino** [comment]
@evgueni-ovtchinnikov try to insert guest addition CD first
![image](https://user-images.githubusercontent.com/14138589/38874199-74feaae8-424f-11e8-8507-1a29f31f2e7c.png)

**Comment by KrisThielemans** [comment]
can we please try `update_VGA.sh` instead to the manual commands? (as a debugging check). still needs you to "insert the CD" as above

**Comment by evgueni-ovtchinnikov** [comment]
tried update_VGA.sh, restarted - no difference

**Comment by paskino** [comment]
did you insert the cd?

**Comment by paskino** [comment]
this https://github.com/CCPPETMR/CCPPETMR_VM/issues/77#issuecomment-382001768

**Comment by evgueni-ovtchinnikov** [comment]
nothing happens when I click there

**Comment by paskino** [comment]
insert the CD clickin' there and then do the `update_VGA.sh` or manual steps

**Comment by KrisThielemans** [comment]
`update_VGA.sh` should error out if it didn't find the Guest Additions CD, so if it didn't, it should have updated your Guest Additions. This is somewhat unlikely to help as it seems that the VGA should be the same version.

**Comment by KrisThielemans** [comment]
@evgueni-ovtchinnikov, what kind of error message are you getting in your console when this happens?

I've just had a case (with the old VM) where it said something like
```
[drm:vbox_bo_push_sysram [vboxvideo]] *ERROR*  unpin bad xxxxxxx
````
with `xxxxxxx` some hexadecimal number.

I found [a post that discusses  this in 2016 with older VBox](https://bbs.archlinux.org/viewtopic.php?id=211331&p=2) which recommends to adding the following to grub.cfg
```
GRUB_CMDLINE_LINUX_DEFAULT="iomem=relaxed"
```
I have no clue if this is still necessary. Let's only try this if you get the same error.

**Comment by paskino** [comment]
The issue was fixed by reinstalling the VGA.

**Comment by KrisThielemans** [comment]
This hasn't fixed the problem. I just did a reboot where the X-server failed to start (blinking screen). I also noticed that the VM captures the mouse (but doesn't display it), which is quite annoying. I can get out of that by pressing the Host key once (right-ctrl on Windows by default). That confirms it's a VGA problem.

I've run `update_VGA.sh`. That does lots of stuff but reports "something went wrong, but proceeding anyway". I don't know what went wrong. I'll do an occasional report and let you know.

@paskino, can you see if you have the same `update_VGA.sh` error and investigate a bit?

**Comment by evgueni-ovtchinnikov** [comment]
had this problem again

solution that worked for me:

cd devel/CCPPETMR_VM/scripts
sudo ./update_VM.sh
click on Devices->Insert Guest Addition CD when prompted to insert CD
reset VM

BTW sudo update_VM.sh in the home folder did not work (did not found the script - without sudo it did, but update failed)

**Comment by KrisThielemans** [comment]
can you check which step in `update_VM.sh` needs `sudo`? I'd like to avoid it as much as possible

**Comment by evgueni-ovtchinnikov** [comment]
sorry, it was update_VGA.sh of course

apparently mount -t iso9660 /dev/sr0 /media/cdrom failed as the last message before the failure was

"CD still not found. Trying /dev/sr0 !"

**Comment by KrisThielemans** [comment]
ok. let's leave this closed as I have no clue what we can do about it :-;

**Comment by paskino** [comment]
What trick?

`update_VGA.sh` didn't work? What's the output?

I have to run it every now and again but so far it's done its job.

**Comment by evgueni-ovtchinnikov** [comment]
please see my comments on sep 28, just above my previous message

**Comment by KrisThielemans** [comment]
closing is we haven't had this in ages, and it's not in our control anyway.
